// Generated by CoffeeScript 1.6.3
(function() {
  var $container, Card, createRandomCard, p1Cards, p2Cards, randomAdj, randomName, randomTitle;

  p1Cards = [];

  p2Cards = [];

  $container = $('#container');

  randomName = function() {
    return _.sample(['kia', 'doug', 'cj', 'bill', 'anitra', 'eric', 'kyle', 'brian']);
  };

  randomAdj = function() {
    return _.sample(['terrifying', 'humongous', 'puny', 'ridiculous', 'average']);
  };

  randomTitle = function() {
    return _.sample(['babooshka', 'jester', 'chicken tosser', 'troll', 'single white man']);
  };

  Card = (function() {
    function Card(title, attack, health, owner) {
      this.title = title;
      this.attack = attack;
      this.health = health;
      this.owner = owner;
      this.$el = $("<div class='card " + this.owner + "'>");
    }

    Card.prototype.render = function() {
      this.$el.html(["<span class='title'>" + this.title + "</span>", "<span class='attack'>a: " + this.attack + "</span>", "<span class='health'>h: " + this.health + "</span>"]);
      return $("#" + this.owner + "Arena").append(this.$el);
    };

    return Card;

  })();

  createRandomCard = function(owner) {
    var adj, attack, health;
    attack = ~~(Math.random() * 3) + 1;
    health = ~~(Math.random() * 3) + 1;
    adj = randomAdj();
    if (adj === 'terrifying' || adj === 'humongous') {
      attack = 4;
    }
    return new Card("" + (randomName()) + " the " + adj + " " + (randomTitle()), attack, health, owner);
  };

  _.times(5, function() {
    p1Cards.push(createRandomCard('p1'));
    return p2Cards.push(createRandomCard('p2'));
  });

  _.forEach(p1Cards, function(item, key, list) {
    return item.render();
  });

  _.forEach(p2Cards, function(item, key, list) {
    return item.render();
  });

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
